# Generated by Django 6.0.6 on 2026-07-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("terminal", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flight",
            options={"ordering": ["-departure_time"]},
        ),
    ]
