# Generated by Django 6.0.6 on 2026-07-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terminal", "0003_alter_flight_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(null=True, upload_to="airplane_image_path/"),
        ),
    ]
